#!/bin/bash

while :
do 
 sleep 1
  oldmem=${mem}
  oldswap=${swap}
  mem=$(free | grep ^Mem | awk '{print $2,$3,$4,$5,$6,$7}')
  swap=$(free | grep ^Swap | awk '{print $2,$3,$4}')
  timestamp=$(date +"%s")
  if [ "$oldmem" != "$mem" ]; then
     mosquitto_pub -q 2 -r -t "systems/${HOSTNAME}/mem" -m "{\"timestamp\":${timestamp},\"values\":[${mem// /,}]}"
  fi
  if [ "$oldswap" != "$swap" ]; then
     mosquitto_pub -q 2 -r -t "systems/${HOSTNAME}/swap" -m "{\"timestamp\":${timestamp},\"values\":[${swap// /,}]}"
  fi
done
